#!/usr/bin/env python3
"""Synthetic regression tests for pilot ChIP-seq peak calling support."""

import importlib.util
import json
import os
import shutil
import tempfile
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]

SPEC = importlib.util.spec_from_file_location(
    "support",
    ROOT / "workflow/scripts/chipseq_peak_calling_support.py",
)

S = importlib.util.module_from_spec(SPEC)
SPEC.loader.exec_module(S)


class PeakCallingTests(unittest.TestCase):

    def setUp(self):
        self.previous = Path.cwd()
        self.temporary = tempfile.TemporaryDirectory()
        os.chdir(self.temporary.name)

        Path("config").mkdir(parents=True)

        shutil.copyfile(
            ROOT / S.CONFIG,
            S.CONFIG,
        )

        cfg = S.load(S.CONFIG)

        S.dump(
            S.PLAN,
            {
                "configuration_sha256": S.sha(S.CONFIG),
                "filtering_evidence": "synthetic",
                "source_root": "/synthetic/source",
                "effective_genome_size": cfg["effective_genome_size"],
                "effective_genome_size_basis": cfg[
                    "effective_genome_size_basis"
                ],
                "reference": {
                    "sha256": "reference",
                    "nuclear_span": cfg["effective_genome_size"],
                },
                "runs": [
                    {
                        "run_accession": cfg["treatment_run"],
                        "role": "ip",
                        "retained_reads": 100,
                        "bam_sha256": "ip",
                        "index_sha256": "ip-index",
                    },
                    {
                        "run_accession": cfg["control_run"],
                        "role": "input",
                        "retained_reads": 80,
                        "bam_sha256": "control",
                        "index_sha256": "control-index",
                    },
                ],
            },
        )

    def tearDown(self):
        os.chdir(self.previous)
        self.temporary.cleanup()

    def write_peak_fixture(self):
        Path("peaks.narrowPeak").write_text(
            "chr1\t100\t200\tpeak1\t100\t.\t5.0\t10.0\t8.0\t50\n"
            "chr1\t300\t500\tpeak2\t200\t.\t10.0\t20.0\t12.0\t100\n"
        )

        Path("summits.bed").write_text(
            "chr1\t150\t151\tpeak1\t100\n"
            "chr1\t400\t401\tpeak2\t200\n"
        )

        Path("peaks.xls").write_text(
            "# This file is generated by MACS3\n"
            "# d = 150\n"
            "chr\tstart\tend\n"
        )

        Path("treat.bdg").write_text("chr1\t0\t10\t1.0\n")
        Path("control.bdg").write_text("chr1\t0\t10\t0.5\n")
        Path("macs3.log").write_text("synthetic MACS3 log\n")
        Path("version.txt").write_text("macs3 3.0.4\n")

        Path("ip_total.txt").write_text("100\n")
        Path("control_total.txt").write_text("80\n")
        Path("ip_overlap.txt").write_text("40\n")
        Path("control_overlap.txt").write_text("8\n")

    def summarize(self):
        S.summarize(
            "peaks.narrowPeak",
            "summits.bed",
            "peaks.xls",
            "treat.bdg",
            "control.bdg",
            "macs3.log",
            "version.txt",
            "ip_total.txt",
            "control_total.txt",
            "ip_overlap.txt",
            "control_overlap.txt",
            "qc.json",
            "qc.tsv",
            "parameters.json",
            "provenance.json",
        )

    def test_peak_statistics_and_frip(self):
        self.write_peak_fixture()
        self.summarize()

        qc = S.load("qc.json")

        self.assertEqual(qc["peak_count"], 2)
        self.assertEqual(qc["union_peak_bp"], 300)
        self.assertEqual(qc["fragment_size_bp"], 147)
        self.assertEqual(
            qc["fragment_size_source"],
            "configured_source_informed_extsize",
        )
        self.assertAlmostEqual(qc["ip_frip"], 0.40)
        self.assertAlmostEqual(qc["input_peak_overlap_fraction"], 0.10)
        self.assertAlmostEqual(qc["ip_to_input_peak_overlap_ratio"], 4.0)

    def test_invalid_summit_offset_rejected(self):
        Path("bad.narrowPeak").write_text(
            "chr1\t100\t200\tpeak1\t100\t.\t5\t10\t8\t100\n"
        )

        with self.assertRaisesRegex(ValueError, "Summit outside peak"):
            S.parse_narrowpeak(
                "bad.narrowPeak",
                "NC_007936.1",
            )

    def test_mitochondrial_peak_rejected(self):
        Path("bad.narrowPeak").write_text(
            "NC_007936.1\t10\t50\tpeak1\t100\t.\t5\t10\t8\t20\n"
        )

        with self.assertRaisesRegex(ValueError, "Mitochondrial peak"):
            S.parse_narrowpeak(
                "bad.narrowPeak",
                "NC_007936.1",
            )

    def test_denominator_disagreement_rejected(self):
        self.write_peak_fixture()
        Path("ip_total.txt").write_text("99\n")

        with self.assertRaisesRegex(ValueError, "IP denominator disagreement"):
            self.summarize()

    def test_stage_verifies_hashes(self):
        source = Path("source")
        source.mkdir()

        Path("input.bam").write_bytes(b"BAM-synthetic")
        Path("input.bam.csi").write_bytes(b"CSI-synthetic")

        shutil.copyfile("input.bam", source / "filtered.bam")
        shutil.copyfile("input.bam.csi", source / "filtered.bam.csi")

        cfg = S.load(S.CONFIG)

        plan = {
            "configuration_sha256": S.sha(S.CONFIG),
            "source_root": str(source.resolve()),
            "runs": [
                {
                    "run_accession": cfg["treatment_run"],
                    "role": "ip",
                    "source_relative": "filtered.bam",
                    "index_relative": "filtered.bam.csi",
                    "bam_sha256": S.sha(source / "filtered.bam"),
                    "index_sha256": S.sha(source / "filtered.bam.csi"),
                    "retained_reads": 100,
                }
            ],
        }

        S.dump("stage_plan.json", plan)

        S.stage(
            cfg["treatment_run"],
            "stage_plan.json",
            "copied/filtered.bam",
            "copied/filtered.bam.csi",
            "copied/report.json",
        )

        report = S.load("copied/report.json")
        self.assertTrue(report["full_input_hash_verified"])

    def test_stage_rejects_changed_input(self):
        source = Path("source")
        source.mkdir()

        (source / "filtered.bam").write_bytes(b"changed")
        (source / "filtered.bam.csi").write_bytes(b"index")

        cfg = S.load(S.CONFIG)

        S.dump(
            "stage_plan.json",
            {
                "configuration_sha256": S.sha(S.CONFIG),
                "source_root": str(source.resolve()),
                "runs": [
                    {
                        "run_accession": cfg["treatment_run"],
                        "role": "ip",
                        "source_relative": "filtered.bam",
                        "index_relative": "filtered.bam.csi",
                        "bam_sha256": "0" * 64,
                        "index_sha256": S.sha(source / "filtered.bam.csi"),
                        "retained_reads": 100,
                    }
                ],
            },
        )

        with self.assertRaisesRegex(ValueError, "SHA-256 mismatch"):
            S.stage(
                cfg["treatment_run"],
                "stage_plan.json",
                "copied/filtered.bam",
                "copied/filtered.bam.csi",
                "copied/report.json",
            )

    def test_publish_copies_and_verifies_outputs(self):
        output = S.OUT
        output.mkdir(parents=True)

        (output / "peak_qc.json").write_text("{}\n")
        (output / "peak_qc.tsv").write_text("test\n")

        Path("saved").mkdir()

        S.publish("saved")

        self.assertTrue(Path("saved/outputs/peak_qc.json").is_file())
        self.assertTrue(Path("saved/output.sha256").is_file())


if __name__ == "__main__":
    unittest.main()
